import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'





export default function Home() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Seba Web Dev Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

<section id='presentation'>

   <h1 className={styles.title}>
         ¡Hola! Mi nombre es
         
        </h1>
      <h2 className={styles.name}>Sebastian.<br></br>
      <span className={styles.sub}>Creo soluciones en la web.</span>
      </h2>
     
        <p className={styles.description}>
        Soy un apasionado desarrollador web FrontEnd, dedicado a crear aplicaciones web altamente responsivas y de excelente rendimiento. Mi objetivo es diseñar experiencias de usuario excepcionales que no solo cumplan con las expectativas, sino que también impulsen y realcen tu producto. Con un enfoque en la innovación y la eficiencia, transformo tus ideas en realidades digitales que destacan.        </p>

      <h2 className={styles.title}>01. <span>Acerca de mi</span></h2>
      <p className={styles.description}>¡Hola! Mi nombre es Sebastián Benítez y soy de Uruguay. Disfruto mucho creando cosas que viven en internet. Mi interés por el desarrollo web comenzó en 2020 con la pandemia de Covid-19. Desde entonces, empecé a aprender muchas cosas sobre FrontEnd, tales como, HTML5, CSS, JavaScript, React, Next.js y Git. A su vez tengo experiencia utilizando CMS como Wordpress. ¡Pero siempre estoy aprendiendo cosas nuevas!

He trabajado en proyectos de distinto tipo, los cuales puedes ver en la sección de proyectos </p>
     <ul className={styles.ul}>
       <li className={styles.li}>NextJs</li>
     <li className={styles.li}>React</li>
     <li className={styles.li}>Javascript</li>
     <li className={styles.li}>Tailwind CSS</li>
     <li className={styles.li}>Html5</li>
     <li className={styles.li}>Wordpress</li>

     </ul>
    
     </section>

     <section id='projects'>
      
     
     <h2 className={styles.title}>02. <span>Proyectos/Trabajos</span></h2>

      <main className={styles.main}>
      
        
      <div className={styles.card}>
            <h2 className={styles.name2}>Fronteras Gaming</h2>
            <p className={styles.description2}>Landing para proyecto de E-Sports en Latam.<br></br>
            Tecnologias: Wordpress</p>
           <a href='https://fronterasgaming.com/'> 
            
           <Image className={styles.img}
      
      src="/fronterasgaming.png"
      alt="Fronteras Gaming"
      unoptimized
      width={300}
      height={300}
      
      layout="intrinsic"
    />
            
            </a> 

          </div>
          <div className={styles.card}>
            <h2 className={styles.name2}>Joyeria Szpigiel</h2>
            <p className={styles.description2}>E-Commerce para joyeria en Argentina.<br></br>
            Tecnologias: Wordpress & Woocomerce</p>
           <a href='https://joyeriaszpigiel.com/'> 
            
           <Image className={styles.img}
      
      src="/joyeriaszpigiel.png"
      alt="Joyeria Szpigiel"
      unoptimized
      width={300}
      height={300}
      layout="intrinsic"
    />
            
            </a> 
          </div>

          <div className={styles.card}>
            <h2 className={styles.name2}>EntreFronterasRP</h2>
            <p className={styles.description2}>Servidor de Roleplay en Fivem.<br></br>
            Lua, VPS, Admin. BD, JavaScript, Html, Css, etc</p>
           <a href='https://www.instagram.com/entrefronterasrp/'> 
            
           <Image className={styles.img}
      
      src="/entrefronterasrp.png"
      alt="EntreFronterasRP"
      unoptimized
      width={300}
      height={300}
      layout="intrinsic"
    />
            
            </a> 
          </div>

          
          <div className={styles.card}>
            <h2 className={styles.name2}>Cars Uruguay</h2>
            <p className={styles.description2}>Recopilacion de autos de una base de datos<br></br>
            Tecnologias: Nextjs & Supabase</p>
           <a href='https://carsuruguay.vercel.app'> 
            
           <Image className={styles.img}
      
      src="/carsuruguay.png"
      alt="CarsUruguay"
      unoptimized
      width={300}
      height={300}
      layout="intrinsic"
    />
            
            </a> 

          </div>

          <div className={styles.card}>
            <h2 className={styles.name2}>Rick y Morty API</h2>
            <p className={styles.description2}>Muestra de personajes de Rick y Morty mediante API.    Tecnologias: Nextjs & Supabase
           </p>
           <a href='https://rickmortyapiniatse.netlify.app'> 
            
           <Image className={styles.img}
      
      src="/rickandmorty.png"
      alt="Rick and Morty"
      width={300}
      height={300}
      unoptimized
      layout="intrinsic"
    />
            
            </a> 
          </div>

          <div className={styles.card}>
            <h2 className={styles.name2}>Coin Niatse</h2>
            <p className={styles.description2}>Listado de las top 100 Criptomonedas en tiempo real<br></br>
            Tecnologias: Html5 Javascript & Css</p>
           <a href='https://coiniatse.netlify.app'> 
            
           <Image className={styles.img}
      
      src="/cripto.png"
      alt="Cripto"
      unoptimized
      width={300}
      height={300}
      layout="intrinsic"

    />
            
            </a> 
          </div>
         
         
      </main>
      </section>
      <section id='contact'>

      <h2 className={styles.title}>03. <span>¿Que sigue?</span></h2>
          <h2 className={styles.name}>Ponerse en contacto
          </h2>
          <p className={styles.description2}>Actualmente estoy buscando proyectos nuevos e interesantes, mi bandeja de entrada está siempre abierta. Si tienes alguna pregunta o simplemente quieres saludar, ¡haré todo lo posible para responderte!</p>
          

      <a className={styles.email} href='malito:sebastianbenitez2505@gmail.com'>Contactame</a>
      <footer className={styles.footer}>
        
          Powered by Seba Web Dev
         
        
      </footer>
      </section>
    </div>
    
  )
}
