import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Seba Web Dev Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


   

      <main className={styles.main}>
      <div className={styles.sky}>
  
  
  <div className={styles.star}></div>
  <div className={styles.star}></div>
  <div className={styles.star}></div>
  <div className={styles.star}></div>
  <div className={styles.star}></div>
  <div className={styles.star}></div>
  <div className={styles.star}></div>
</div>
        <h1 className={styles.title}>
          Sebastian Web developer
        </h1>

        <p className={styles.description}>
          Hey! I'm Sebastian👋
          
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>About me</h2>
            <p>I'm a Frontend Developer, who is always learning. With a strong passion for building responsive and performant web applications with great user experiences that positively impacts the world</p>
          </div>

         
          <div className={styles.card}>
            <h2>My stack</h2>
            <p>Now a days i'm working with Nextjs, Reactjs, Javscript, Html5, Css, Tailwind CSS and Git</p>
          </div>
          
          <div className={styles.card}>
            <h2>My projects</h2>
            <p>Here you can see some of my projects...</p>
          </div>
          </div>
          
          <div className={styles.card}>
            <h2>Cars Uruguay</h2>
            <p>This project show cars from a database<br></br>
            Stack used: Nextjs And Supabase</p>
           <a href='https://carsuruguay.vercel.app'> 
            
           <Image className={styles.img}
      
      src="/carsuruguay.png"
      alt="CarsUruguay"
      width={300}
      height={300}
    />
            
            </a> 
    <a href='https://github.com/Niatse/Galeria-Imagenes'>Github Repository</a>
          </div>

          <div className={styles.card}>
            <h2>Rick And Morty API</h2>
            <p>This page shows the characters from Rick and Morty from and API<br></br>
            Stack used: Nextjs And Supabase</p>
           <a href='https://rickmortyapiniatse.netlify.app'> 
            
           <Image className={styles.img}
      
      src="/rickandmorty.png"
      alt="Rick and Morty"
      width={300}
      height={300}
    />
            
            </a> 
    <a href='https://github.com/Niatse/Uso-de-api-Rick-and-Morty'>Github Repository</a>
          </div>

          <div className={styles.card}>
            <h2>Coin Niatse</h2>
            <p>This project show the top 100 cryptos<br></br>
            Stack used: Html5 Javascript & Css</p>
           <a href='https://coiniatse.netlify.app'> 
            
           <Image className={styles.img}
      
      src="/cripto.png"
      alt="CarsUruguay"
      width={300}
      height={300}
    />
            
            </a> 
    <a href='https://github.com/Niatse/CoinNiatse-Prod'>Github Repository</a>
          </div>
          <div className={styles.card}><a href='malito:gameerseba@gmail.com'>Contact me</a></div>
          
      </main>

      <footer className={styles.footer}>
        
          Powered by Seba Web Dev
         
        
      </footer>
    </div>
  )
}
